import { useState, useRef, useEffect, useCallback, type ReactNode } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Droplets, ArrowDown, GitCompare, Globe, GraduationCap } from 'lucide-react';
import QuizMode, { type QuizQuestion } from '../../shared/QuizMode';

type ViewMode = 'transpiration' | 'root-pressure' | 'xylem-phloem' | 'ghana' | 'quiz';

const QUIZ_QUESTIONS: QuizQuestion[] = [
  { id: 'wt1', question: 'Which tissue is responsible for transporting water in plants?', type: 'multiple-choice', options: ['Phloem', 'Xylem', 'Epidermis', 'Cortex'], correctAnswer: 'Xylem', explanation: 'Xylem vessels transport water and dissolved minerals from roots to leaves. Phloem transports sugars.' },
  { id: 'wt2', question: 'Transpiration mainly occurs through which structure?', type: 'multiple-choice', options: ['Lenticels', 'Stomata', 'Cuticle', 'Root hairs'], correctAnswer: 'Stomata', explanation: 'Most transpiration occurs through stomata — small pores mainly on the underside of leaves, controlled by guard cells.' },
  { id: 'wt3', question: 'Root pressure is generated by:', type: 'multiple-choice', options: ['Osmosis of water into root cells', 'Active transport of ions into xylem', 'Capillary action', 'Cohesion-tension'], correctAnswer: 'Active transport of ions into xylem', explanation: 'Root cells actively transport mineral ions into the xylem, lowering water potential and drawing water in by osmosis, creating pressure.' },
  { id: 'wt4', question: 'The cohesion-tension theory explains:', type: 'multiple-choice', options: ['How sugars are transported', 'How water moves up xylem', 'How roots absorb minerals', 'How stomata open'], correctAnswer: 'How water moves up xylem', explanation: 'Cohesion (water molecules sticking together) and tension (pull from transpiration) draw water up through xylem vessels continuously.' },
  { id: 'wt5', question: 'Phloem transports:', type: 'multiple-choice', options: ['Water only', 'Minerals only', 'Sugars (sucrose) and amino acids', 'Oxygen'], correctAnswer: 'Sugars (sucrose) and amino acids', explanation: 'Phloem transports organic substances (mainly sucrose and amino acids) from source (leaves) to sink (roots, fruits).' },
  { id: 'wt6', question: 'Which environmental factor increases transpiration rate?', type: 'multiple-choice', options: ['High humidity', 'Low temperature', 'High wind speed', 'Low light'], correctAnswer: 'High wind speed', explanation: 'Wind removes water vapour from around the leaf, increasing the water vapour gradient and thus transpiration rate.' },
  { id: 'wt7', question: 'Guttation occurs when:', type: 'multiple-choice', options: ['Transpiration is high', 'Root pressure is high and transpiration is low', 'Phloem is blocked', 'Stomata are closed permanently'], correctAnswer: 'Root pressure is high and transpiration is low', explanation: 'Guttation (water droplets at leaf edges) occurs when root pressure pushes water up but low transpiration cannot remove it fast enough.' },
  { id: 'wt8', question: 'Xylem vessels are strengthened by:', type: 'multiple-choice', options: ['Cellulose only', 'Lignin', 'Suberin', 'Cutin'], correctAnswer: 'Lignin', explanation: 'Lignin waterproofs and strengthens xylem vessel walls, preventing collapse under the tension of water transport.' },
];

function TranspirationStream() {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const animRef = useRef<number>(0);
  const timeRef = useRef(0);
  interface WaterParticle { x: number; y: number; speed: number; path: number }
  const particles = useRef<WaterParticle[]>([]);

  useEffect(() => {
    particles.current = [];
    for (let i = 0; i < 20; i++) {
      particles.current.push({ x: 0, y: 0, speed: 0.3 + Math.random() * 0.5, path: Math.random() });
    }
    const draw = () => {
      const canvas = canvasRef.current;
      if (!canvas) return;
      const ctx = canvas.getContext('2d');
      if (!ctx) return;
      timeRef.current += 0.016;
      const t = timeRef.current;
      const W = 300, H = 380;
      ctx.clearRect(0, 0, W, H);

      ctx.fillStyle = '#06090f';
      ctx.fillRect(0, 0, W, H);

      ctx.strokeStyle = 'rgba(34,211,238,0.15)';
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.moveTo(150, 350);
      ctx.lineTo(150, 200);
      ctx.lineTo(150, 80);
      ctx.lineTo(120, 40);
      ctx.stroke();

      ctx.strokeStyle = 'rgba(34,211,238,0.1)';
      ctx.lineWidth = 8;
      ctx.beginPath();
      ctx.moveTo(150, 350);
      ctx.lineTo(150, 80);
      ctx.stroke();

      ctx.fillStyle = 'rgba(34,211,238,0.05)';
      for (let i = 0; i < 6; i++) {
        const angle = (i / 6) * Math.PI * 2;
        const cx = 150 + Math.cos(angle) * 15;
        const cy = 360 + Math.sin(angle) * 10;
        ctx.beginPath();
        ctx.moveTo(cx, cy);
        ctx.quadraticCurveTo(cx, cy - 40, 150, 330);
        ctx.stroke();
      }

      ctx.strokeStyle = 'rgba(34,211,238,0.3)';
      ctx.lineWidth = 1;
      ctx.beginPath();
      ctx.ellipse(150, 35, 40, 18, 0, 0, Math.PI * 2);
      ctx.stroke();
      ctx.beginPath();
      ctx.ellipse(150, 35, 55, 25, 0, 0, Math.PI * 2);
      ctx.stroke();

      for (let i = 0; i < 3; i++) {
        const yOff = -10 - i * 15;
        const xOff = 50 + i * 15;
        ctx.strokeStyle = 'rgba(34,211,238,0.15)';
        ctx.lineWidth = 0.8;
        ctx.beginPath();
        ctx.moveTo(150, 35);
        ctx.quadraticCurveTo(150 + xOff, 35 + yOff - 20, 150 + xOff + 20, 35 + yOff - 30);
        ctx.stroke();
      }

      particles.current.forEach(p => {
        const progress = ((t * p.speed * 0.3) % 1);
        const y = 360 - progress * 340;
        const x = 150 + Math.sin(y * 0.05 + p.path * 10) * 3;
        p.x = x; p.y = y;
        const alpha = Math.min(1, progress * 3) * Math.min(1, (1 - progress) * 3);
        ctx.beginPath();
        ctx.arc(x, y, 2.5, 0, Math.PI * 2);
        ctx.fillStyle = `rgba(34, 211, 238, ${alpha * 0.8})`;
        ctx.fill();
      });

      ctx.fillStyle = 'rgba(255,255,255,0.15)';
      ctx.font = '8px monospace';
      ctx.textAlign = 'center';
      ctx.fillText('ROOT', 150, 375);
      ctx.fillText('STEM (XYLEM)', 150, 190);
      ctx.fillText('LEAF', 150, 20);

      animRef.current = requestAnimationFrame(draw);
    };
    draw();
    return () => cancelAnimationFrame(animRef.current);
  }, []);

  return (
    <div className="flex flex-col gap-5 max-w-3xl mx-auto">
      <div className="flex justify-center">
        <div className="bg-black/60 rounded-2xl border border-brand-border p-2">
          <canvas ref={canvasRef} width={300} height={380} className="rounded-xl" />
        </div>
      </div>
      <div className="grid grid-cols-3 gap-3">
        {[
          { label: 'Root Uptake', desc: 'Root hairs absorb water by osmosis' },
          { label: 'Cohesion-Tension', desc: 'Water molecules pull each other upward' },
          { label: 'Transpiration Pull', desc: 'Evaporation from leaf creates suction' },
        ].map(item => (
          <div key={item.label} className="bg-slate-900/60 rounded-xl p-3 border border-slate-800">
            <div className="text-[10px] text-brand-accent font-bold uppercase tracking-widest mb-1">{item.label}</div>
            <div className="text-slate-400 text-xs">{item.desc}</div>
          </div>
        ))}
      </div>
    </div>
  );
}

function RootPressure() {
  const [showLabels, setShowLabels] = useState(true);
  return (
    <div className="flex flex-col gap-5 max-w-3xl mx-auto">
      <div className="flex justify-end">
        <button onClick={() => setShowLabels(!showLabels)}
          className={`px-3 py-1.5 rounded-lg text-xs font-bold uppercase tracking-widest transition-all ${showLabels ? 'bg-brand-accent text-black' : 'bg-slate-800 text-slate-400'}`}
        >Toggle Labels</button>
      </div>
      <div className="bg-slate-900/60 rounded-2xl border border-brand-border p-6 flex justify-center">
        <svg viewBox="0 0 300 250" width={300} height={250}>
          <ellipse cx={150} cy={125} rx={90} ry={80} fill="none" stroke="rgba(139,92,246,0.3)" strokeWidth={2} />
          <ellipse cx={150} cy={125} rx={60} ry={50} fill="none" stroke="rgba(139,92,246,0.2)" strokeWidth={1.5} strokeDasharray="4 3" />
          <ellipse cx={150} cy={125} rx={30} ry={22} fill="rgba(139,92,246,0.1)" stroke="rgba(139,92,246,0.4)" strokeWidth={1.5} />
          {[
            { x: 50, y: 80, angle: -0.5 },
            { x: 60, y: 160, angle: 0.3 },
            { x: 245, y: 90, angle: 0.6 },
            { x: 240, y: 155, angle: -0.4 },
            { x: 100, y: 195, angle: 0.7 },
            { x: 200, y: 195, angle: -0.7 },
          ].map((root, i) => (
            <g key={i}>
              <line x1={root.x} y1={root.y} x2={root.x + Math.cos(root.angle) * 30} y2={root.y + Math.sin(root.angle) * 25}
                stroke="rgba(139,92,246,0.4)" strokeWidth={2} strokeLinecap="round" />
              <line x1={root.x + Math.cos(root.angle) * 30} y1={root.y + Math.sin(root.angle) * 25}
                x2={root.x + Math.cos(root.angle) * 50} y2={root.y + Math.sin(root.angle) * 45}
                stroke="rgba(139,92,246,0.25)" strokeWidth={1.5} strokeLinecap="round" />
            </g>
          ))}
          {[
            { x: 20, y: 70 }, { x: 25, y: 165 }, { x: 270, y: 85 }, { x: 265, y: 165 },
            { x: 95, y: 210 }, { x: 210, y: 210 },
          ].map((hair, i) => (
            <g key={`h${i}`}>
              <line x1={hair.x} y1={hair.y} x2={hair.x - 10} y2={hair.y + 3}
                stroke="rgba(34,211,238,0.3)" strokeWidth={0.8} />
              <line x1={hair.x} y1={hair.y} x2={hair.x - 8} y2={hair.y - 5}
                stroke="rgba(34,211,238,0.3)" strokeWidth={0.8} />
            </g>
          ))}
          <motion.g animate={{ y: [0, -5, 0] }} transition={{ duration: 2, repeat: Infinity }}>
            <line x1={150} y1={100} x2={150} y2={45} stroke="#22d3ee" strokeWidth={3} />
            <polygon points="145,48 155,48 150,38" fill="#22d3ee" />
          </motion.g>
          {showLabels && (
            <>
              <text x={150} y={135} textAnchor="middle" fontSize="8" fill="rgba(139,92,246,0.8)" fontWeight="bold">PERICYCLE</text>
              <text x={150} y={175} textAnchor="middle" fontSize="8" fill="rgba(139,92,246,0.6)">ENDODERMIS</text>
              <text x={150} y={205} textAnchor="middle" fontSize="8" fill="rgba(139,92,246,0.4)">CORTEX</text>
              <text x={150} y={225} textAnchor="middle" fontSize="8" fill="rgba(139,92,246,0.3)">EPIDERMIS</text>
              <text x={150} y={32} textAnchor="middle" fontSize="8" fill="#22d3ee" fontWeight="bold">XYLEM</text>
            </>
          )}
        </svg>
      </div>
      <div className="bg-black/40 rounded-xl p-4 border border-slate-800">
        <div className="text-[10px] text-brand-accent font-bold uppercase tracking-widest mb-2">How Root Pressure Works</div>
        <div className="text-slate-300 text-sm space-y-2">
          <p>1. Root hair cells actively transport mineral ions into the root cortex</p>
          <p>2. This lowers the water potential inside the xylem</p>
          <p>3. Water enters by osmosis, creating positive pressure</p>
          <p>4. This pressure pushes water upward through the xylem</p>
        </div>
      </div>
    </div>
  );
}

function XylemPhloem() {
  const [revealed, setRevealed] = useState<Record<string, boolean>>({});
  const features = [
    { feature: 'Direction', xylem: 'Upward only (roots → leaves)', phloem: 'Both directions (source ↔ sink)' },
    { feature: 'Transports', xylem: 'Water + mineral ions', phloem: 'Sucrose + amino acids' },
    { feature: 'Cell type', xylem: 'Dead, hollow vessels', phloem: 'Living sieve tube elements + companion cells' },
    { feature: 'Strengthening', xylem: 'Lignin (waterproof & rigid)', phloem: 'No lignin (thin cellulose walls)' },
    { feature: 'End walls', xylem: 'Broken down (continuous tube)', phloem: 'Sieve plates with pores' },
    { feature: 'Mechanism', xylem: 'Cohesion-tension (passive)', phloem: 'Mass flow / active transport' },
    { feature: 'Position', xylem: 'Inner (closer to centre)', phloem: 'Outer (closer to epidermis)' },
    { feature: 'Cytoplasm', xylem: 'None (empty lumen)', phloem: 'Thin layer of cytoplasm' },
  ];
  return (
    <div className="flex flex-col gap-5 max-w-3xl mx-auto">
      <div className="bg-slate-900/60 rounded-2xl border border-brand-border overflow-hidden">
        <div className="grid grid-cols-3 gap-0 text-xs font-bold uppercase tracking-widest p-4 border-b border-slate-800">
          <div className="text-slate-500">Feature</div>
          <div className="text-center text-cyan-400">Xylem</div>
          <div className="text-center text-green-400">Phloem</div>
        </div>
        {features.map((row, i) => (
          <div key={row.feature} className="grid grid-cols-3 gap-0 p-4 text-sm border-b border-slate-800/50 cursor-pointer hover:bg-slate-800/20"
            onClick={() => setRevealed(prev => ({ ...prev, [row.feature]: !prev[row.feature] }))}
          >
            <div className="text-slate-400 font-medium text-xs">{row.feature}</div>
            <div className="text-center text-xs">
              {revealed[row.feature]
                ? <span className="text-cyan-300 font-mono">{row.xylem}</span>
                : <span className="text-slate-600">Click to reveal</span>}
            </div>
            <div className="text-center text-xs">
              {revealed[row.feature]
                ? <span className="text-green-300 font-mono">{row.phloem}</span>
                : <span className="text-slate-600">Click to reveal</span>}
            </div>
          </div>
        ))}
      </div>
      <button onClick={() => setRevealed(Object.fromEntries(features.map(f => [f.feature, true])))}
        className="px-4 py-2 bg-brand-accent text-black rounded-lg text-xs font-bold uppercase tracking-widest hover:bg-white transition-all self-center"
      >Reveal All</button>
    </div>
  );
}

function GhanaContext() {
  const cards = [
    { id: 'cocoa', title: 'Cocoa Shade Trees', icon: '🌳', color: '#86efac',
      context: 'Shade trees in cocoa farms (e.g., Terminalia superba) reduce transpiration in cacao seedlings by blocking direct sunlight. This maintains higher humidity around leaves, reducing the water vapour gradient and slowing water loss.',
      fact: 'Ghana is the 2nd largest cocoa producer. Shade-grown cocoa uses 30% less water.' },
    { id: 'forest', title: 'Forest Reserves & Transpiration', icon: '🌲', color: '#4ade80',
      context: 'Ghana\'s Atewa Forest Reserve acts as a "water tower". Trees transpire millions of litres daily, contributing to rainfall patterns. Deforestation breaks this cycle, reducing regional rainfall.',
      fact: 'A single large tree can transpire 400+ litres of water per day.' },
    { id: 'irrigation', title: 'Irrigation in Northern Ghana', icon: '💧', color: '#60a5fa',
      context: 'In the Sahel zone, farmers use drip irrigation to minimise transpiration losses. Water is delivered directly to roots, reducing evaporation from soil surfaces.',
      fact: 'Drip irrigation can save up to 70% water compared to flood irrigation.' },
  ];
  const [expanded, setExpanded] = useState<string | null>(null);
  return (
    <div className="flex flex-col gap-5 max-w-3xl mx-auto">
      <div className="text-center mb-2">
        <h2 className="text-2xl font-light text-white">Water Transport in <span className="text-brand-accent font-medium">Ghana</span></h2>
      </div>
      {cards.map(card => (
        <div key={card.id} className="bg-slate-900/60 rounded-2xl border border-brand-border overflow-hidden">
          <div className="p-5 cursor-pointer hover:bg-slate-800/30 transition-colors" onClick={() => setExpanded(expanded === card.id ? null : card.id)}>
            <div className="flex items-center gap-3">
              <span className="text-3xl">{card.icon}</span>
              <div>
                <h3 className="text-white font-bold">{card.title}</h3>
                <p className="text-slate-400 text-sm">{card.context.slice(0, 60)}...</p>
              </div>
            </div>
          </div>
          <AnimatePresence>
            {expanded === card.id && (
              <motion.div initial={{ height: 0, opacity: 0 }} animate={{ height: 'auto', opacity: 1 }} exit={{ height: 0, opacity: 0 }} className="overflow-hidden border-t border-slate-800">
                <div className="p-5 space-y-3">
                  <p className="text-slate-300 text-sm">{card.context}</p>
                  <div className="bg-green-500/10 border border-green-500/20 rounded-xl p-3">
                    <span className="text-[10px] text-green-400 font-bold uppercase tracking-widest">Key Fact</span>
                    <p className="text-green-300 text-sm mt-1">{card.fact}</p>
                  </div>
                </div>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      ))}
    </div>
  );
}

export default function WaterTransport() {
  const [viewMode, setViewMode] = useState<ViewMode>('transpiration');

  const MODES: { key: ViewMode; label: string; icon: ReactNode }[] = [
    { key: 'transpiration', label: 'Transpiration', icon: <Droplets size={14} /> },
    { key: 'root-pressure', label: 'Root Pressure', icon: <ArrowDown size={14} /> },
    { key: 'xylem-phloem', label: 'Xylem vs Phloem', icon: <GitCompare size={14} /> },
    { key: 'ghana', label: 'Ghana', icon: <Globe size={14} /> },
    { key: 'quiz', label: 'Quiz', icon: <GraduationCap size={14} /> },
  ];

  return (
    <div className="flex flex-col items-center justify-start w-full min-h-[600px] p-6 relative bg-[#06090f] rounded-3xl">
      <div className="absolute top-4 left-4 flex flex-wrap gap-2 z-20">
        {MODES.map(({ key, label, icon }) => (
          <button key={key} onClick={() => setViewMode(key)}
            className={`flex items-center gap-2 px-3 py-2 rounded-lg text-xs font-bold uppercase tracking-widest transition-all ${viewMode === key ? 'bg-brand-accent text-black' : 'bg-slate-800/80 text-slate-400 hover:text-white'}`}
          >{icon} {label}</button>
        ))}
      </div>
      <div className="w-full mt-14">
        <AnimatePresence mode="wait">
          <motion.div key={viewMode} initial={{ opacity: 0, y: 16 }} animate={{ opacity: 1, y: 0 }} exit={{ opacity: 0, y: -16 }} transition={{ duration: 0.3 }}>
            {viewMode === 'transpiration' && <TranspirationStream />}
            {viewMode === 'root-pressure' && <RootPressure />}
            {viewMode === 'xylem-phloem' && <XylemPhloem />}
            {viewMode === 'ghana' && <GhanaContext />}
            {viewMode === 'quiz' && <div className="max-w-xl mx-auto"><QuizMode questions={QUIZ_QUESTIONS} title="Water Transport Quiz" /></div>}
          </motion.div>
        </AnimatePresence>
      </div>
      <div className="w-full mt-6 bg-brand-accent/5 border border-brand-accent/20 rounded-xl p-4 text-xs text-slate-400">
        <span className="text-brand-accent font-bold text-[9px] uppercase tracking-widest">Exam Note · WAEC · </span>
Know the cohesion-tension theory, the role of root pressure, and the differences between xylem and phloem. WASSCE frequently tests transpiration factors and plant tissue identification.
      </div>
    </div>
  );
}
